# Generated by Django 4.0.5 on 2022-06-06 05:02

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(max_length=30)),
                ('code', models.TextField(max_length=2, unique=True, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z]*$', 'Only alphanumeric characters are allowed.')])),
                ('icon', models.ImageField(upload_to='state_icons')),
                ('added', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
