# Generated by Django 4.0.5 on 2022-06-06 05:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0002_question_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='state',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='quickstart.state'),
        ),
    ]
